CREATE TABLE sop_generation_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    requested_title VARCHAR(255) NOT NULL,
    instructions TEXT,
    roles TEXT NOT NULL,
    status VARCHAR(255) NOT NULL,
    result_sop_id BIGINT,
    error_message TEXT,
    created_at TIMESTAMP(6) NOT NULL,
    started_at TIMESTAMP(6),
    completed_at TIMESTAMP(6),
    CONSTRAINT fk_sop_generation_jobs_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_sop_generation_jobs_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT fk_sop_generation_jobs_result_sop FOREIGN KEY (result_sop_id) REFERENCES sops(id) ON DELETE SET NULL
);

CREATE TABLE sop_generation_job_documents (
    job_id BIGINT NOT NULL,
    document_id BIGINT NOT NULL,
    PRIMARY KEY (job_id, document_id),
    CONSTRAINT fk_sop_generation_job_documents_job FOREIGN KEY (job_id) REFERENCES sop_generation_jobs(id) ON DELETE CASCADE,
    CONSTRAINT fk_sop_generation_job_documents_document FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE
);

CREATE INDEX idx_sop_generation_jobs_company_created_at
    ON sop_generation_jobs(company_id, created_at DESC);

CREATE INDEX idx_sop_generation_jobs_owner_id
    ON sop_generation_jobs(owner_id);
