CREATE TABLE sop_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sop_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    title VARCHAR(255) NOT NULL,
    purpose TEXT,
    scope TEXT,
    procedure_text TEXT,
    roles TEXT,
    status VARCHAR(255) NOT NULL,
    created_by_id BIGINT NOT NULL,
    change_reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_sop_versions_sop FOREIGN KEY (sop_id) REFERENCES sops(id) ON DELETE CASCADE,
    CONSTRAINT fk_sop_versions_created_by FOREIGN KEY (created_by_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_sop_versions_sop_version UNIQUE (sop_id, version_number)
);

CREATE INDEX idx_sop_versions_sop_id ON sop_versions(sop_id);
CREATE INDEX idx_sop_versions_created_by_id ON sop_versions(created_by_id);
