CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id BIGINT NOT NULL,
    original_file_name VARCHAR(255),
    stored_file_name VARCHAR(255),
    file_type VARCHAR(255),
    file_size BIGINT,
    storage_url VARCHAR(255),
    uploaded_at TIMESTAMP(6),
    extracted_text TEXT,
    text_extracted_at TIMESTAMP(6),
    extraction_status VARCHAR(255),
    CONSTRAINT fk_documents_owner
        FOREIGN KEY (owner_id)
        REFERENCES users (id)
);

CREATE INDEX idx_documents_owner_id ON documents (owner_id);
