CREATE TABLE sops (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    purpose TEXT,
    scope TEXT,
    procedure_text TEXT,
    roles TEXT,
    source_document_id BIGINT NOT NULL,
    owner_id BIGINT NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_sops_source_document FOREIGN KEY (source_document_id) REFERENCES documents(id) ON DELETE CASCADE,
    CONSTRAINT fk_sops_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_sops_source_document_id ON sops(source_document_id);
CREATE INDEX idx_sops_owner_id ON sops(owner_id);
