CREATE TABLE sop_source_chunks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sop_id BIGINT NOT NULL,
    document_chunk_id BIGINT NOT NULL,
    score INTEGER NOT NULL,
    matched_terms TEXT NOT NULL,
    CONSTRAINT fk_sop_source_chunks_sop
        FOREIGN KEY (sop_id)
        REFERENCES sops(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_sop_source_chunks_document_chunk
        FOREIGN KEY (document_chunk_id)
        REFERENCES document_chunks(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_sop_source_chunks_sop_id ON sop_source_chunks(sop_id);
CREATE INDEX idx_sop_source_chunks_document_chunk_id ON sop_source_chunks(document_chunk_id);
