CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE company_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_company_members_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_company_members_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    CONSTRAINT uk_company_members_company_user UNIQUE (company_id, user_id)
);

ALTER TABLE documents
    ADD COLUMN company_id BIGINT;

ALTER TABLE documents
    ADD CONSTRAINT fk_documents_company FOREIGN KEY (company_id) REFERENCES companies(id);

ALTER TABLE sops
    ADD COLUMN company_id BIGINT;

ALTER TABLE sops
    ADD CONSTRAINT fk_sops_company FOREIGN KEY (company_id) REFERENCES companies(id);

CREATE INDEX idx_company_members_user_id ON company_members(user_id);
CREATE INDEX idx_company_members_company_id ON company_members(company_id);
CREATE INDEX idx_documents_company_id ON documents(company_id);
CREATE INDEX idx_sops_company_id ON sops(company_id);
